### ISSUE TITLE
Qusetions about your paper

### ISSUE THREAD

**Issue by slcheng97** [xiaomabufei/SKDF#1]
Thank you for your great work!  Here, I had a question regarding equation 8-10 in your original manuscript:
<img width="617" alt="截屏2023-03-22 20 54 57" src="https://user-images.githubusercontent.com/27549848/226910954-a6509a0e-091d-4ff2-9c13-d1b6a4b34c39.png">
Could you please explain the difference between $l_z$ and $l_p$? I am trying to understand this concept better, and I would appreciate your guidance on this matter.

**Comment by slcheng97** [comment]
Besides, I'm also curious about whether the pseudo-label is generated by the model itself. Are you suggesting that the box score output from the box head will be used to supervise the classification score output from the classification head?
<img width="592" alt="截屏2023-03-22 21 02 42" src="https://user-images.githubusercontent.com/27549848/226914907-af31625d-b9e2-4e73-a952-87f1cd2509a9.png">

**Comment by xiaomabufei** [comment]
These two represent the unknown labels form VL pre_trained model and pseudo labels, respectively. 
Morever, I guarantee that the box score output from the box head will be used to supervise the classification score output from the classification head.
The code is coming soon!!

**Comment by slcheng97** [comment]
Thank you very much for your prompt and helpful response. Your timely reply has addressed all of my questions
